issuer: https://dex.gde.gigsternetwork.com:5556
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key

# Uncomment this block to enable configuration for the expiration time durations.
expiry:
  signingKeys: "24h"
  idTokens: "26300h"

# Options for controlling the logger.
logger:
  level: "debug"
  format: "text" # can also be "json"

connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: https://dex.gde.gigsternetwork.com:5556/callback
    # Optional organizations and teams, communicated through the "groups" scope.
    #
    # NOTE: This is an EXPERIMENTAL config option and will likely change.
    #
    # Legacy 'org' field. 'org' and 'orgs' cannot be used simultaneously. A user
    # MUST be a member of the following org to authenticate with dex.
    # org: my-organization
    #
    # Dex queries the following organizations for group information if the
    # "groups" scope is provided. Group claims are formatted as "(org):(team)".
    # For example if a user is part of the "engineering" team of the "coreos"
    # org, the group claim would include "coreos:engineering".
    #
    # A user MUST be a member of at least one of the following orgs to
    # authenticate with dex.
    org: gigster-eng
oauth2:
  skipApprovalScreen: true

staticClients:
- id: example-app
  redirectURIs:
  - 'https://signin.gde.gigsternetwork.com/callback'
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true
